import Head from "next/head";
import Feed from "../containers/Feed";
import Sidebar from "../containers/Sidebar";
import Widgets from "../containers/Widgets";

export default function Home() {
  return (
    <div className="flex h-screen w-screen select-none justify-center overflow-hidden bg-[#15202b] text-white">
      <Head>
        <title>Twitter Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-3/4 max-w-[1400px] justify-between">
        <Sidebar />
        <Feed />
        <Widgets />
      </div>
    </div>
  );
}
